apiVersion: v1
kind: Secret
metadata:
  name: ${environment}-${serviceName}
  namespace: ${environment}-${serviceName}
type: Opaque
stringData:
  APP_KEY: ""
  REDIS_PASSWORD: "null"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_KEY: ""