apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptemplate-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptemplate-controller
  template:
    metadata:
      labels:
        app: apptemplate-controller
    spec:
      containers:
        - name: apptemplate
          image: drayfocus/apptemplate-controller:1.36
          ports:
            - containerPort: 8080
          imagePullPolicy: Always